### ISSUE TITLE
The Naming of "custom_objects"

### ISSUE THREAD

**Issue by imyzc** [titu1994/tf_SIREN#9]
Hi, about the source code of "siren.py",

```
tf.keras.utils.get_custom_objects().update({
    'sine': Sine,
    'siren_uniform': SIRENInitializer,
    'siren_first_uniform': SIRENFirstLayerInitializer,
    'SinusodialRepresentationDense': SinusodialRepresentationDense,
    'ScaledSinusodialRepresentationDense': ScaledSinusodialRepresentationDense,
})
```

I think the purpose of the code is to make custom object available by calling "tf.keras.utils.get_custom_objects()".

Therefore I would like to ask why the name declared be like 
"sine" but not "Sine";
"siren_uniform" but not "SIRENInitializer"; 
"siren_first_uniform" but not "SIRENFirstLayerInitializer"?

I think it should be like

```
tf.keras.utils.get_custom_objects().update({
    'Sine': Sine,
    'SIRENInitializer': SIRENInitializer,
    'SIRENFirstLayerInitializer': SIRENFirstLayerInitializer,
    'SinusodialRepresentationDense': SinusodialRepresentationDense,
    'ScaledSinusodialRepresentationDense': ScaledSinusodialRepresentationDense,
})
```

And loading model can be achieved by utilizing
```
load_model =
keras.models.load_model('./weight_model.h5',custom_objects=tf.keras.utils.get_custom_objects())
```

Cuz the native name of the class usually be like: `Sine.__name__ = "Sine"`

Is there other purpose intended to be done, so that we cannot use the origin class name directly?
Thank you!

**Comment by titu1994** [comment]
You are confusing a few things. Names for custom objects are not exactly important, as long as they are called with the current name always in your own code. 

Look at how the activation functions are defined, they are all lower case in Keras, so sine is more appropriate than Sine when passing to Activation().

Same with initializers. The actual class of the model or layer that needs to be resolved however just have the same name, so that Keras can resolve it during class creation. Look at custom activation functions for this example.

**Comment by imyzc** [comment]
> You are confusing a few things. Names for custom objects are not exactly important, as long as they are called with the current name always in your own code.
> 
> Look at how the activation functions are defined, they are all lower case in Keras, so sine is more appropriate than Sine when passing to Activation().
> 
> Same with initializers. The actual class of the model or layer that needs to be resolved however just have the same name, so that Keras can resolve it during class creation. Look at custom activation functions for this example.

I get it! Thanks a lot!
